### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by MasterWindowS** [mEldevlp/surfcombat-metamod-cs2#1]
Hi, I have this error when i try compile

![image](https://github.com/mEldevlp/surfcombat-metamod-cs2/assets/71204342/5eab14ca-7289-4f1d-9800-b853a1292eaa)

**Comment by MasterWindowS** [comment]
![image](https://github.com/mEldevlp/surfcombat-metamod-cs2/assets/71204342/d627f4d0-12c8-41a2-aa20-2a4f4a6c7802)

The file misc.spp is not in the directory

**Comment by mEldevlp** [comment]
Fix it in [#10cec77862](https://github.com/mEldevlp/surfcombat-metamod-cs2/tree/10cec778623a21782fdcc8a7bb25742d081cc229) commit. I recommend using msvc.

Thanks.
