### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Septembers** [mEldevlp/surfcombat-metamod-cs2#2]
Hello. What's wrong? I follow the instructions in the readme

/root/surfcombat-metamod-cs2/src/utils/entity/ccsplayercontroller.h: In member function ‘void CCSPlayerController::m_bPawnIsAlive_prop::Set(bool)’:
/root/surfcombat-metamod-cs2/src/utils/schema.h:86:63: error: ‘offsetof’ within non-standard-layout type ‘CCSPlayerController::ThisClass’ {aka ‘CCSPlayerController’} is conditionally-supported [-Werror=invalid-offsetof]
   86 |                         static const size_t offset = offsetof(ThisClass, varName);                                                                                                              \

**Comment by Septembers** [comment]
Build failed: surfcombatcs2/linux-x86_64/_root_surfcombat_metamod_cs2_src_surf_sc_player.d

**Comment by mEldevlp** [comment]
Greetings! 

I put a compilable project on linux in the [master](https://github.com/mEldevlp/surfcombat-metamod-cs2) branch, try it. If it doesnt work check your submodules, I guess they wrong cloned
