### ISSUE TITLE
Failed to load plugin on linux

### ISSUE THREAD

**Issue by juandrep** [mEldevlp/surfcombat-metamod-cs2#4]
Hello, i'm trying too use the version of linux for the server but is give-me an error on the console of the metta list tell is failed too load

meta list
Listing 3 plugins:
  [01] CounterStrikeSharp (0.1.0) by Roflmuffin
  [02] Movement Unlocker (1.0) by Vauff
  [03] FAILED

meta load 3
Failed to load plugin 3 (File not found: /home/andremar2449/185.113.141.55-22101/game/csgo/3.so).

**Comment by mEldevlp** [comment]
Hello,

Some signatures on linux may not work, because every update of cs2 move them. I apologize for no work on linux, I have no way to test plugin on another OS. I take all signatures from [CS2Fixes](https://github.com/Source2ZE/CS2Fixes)

But on windows, I guarantee that the plugin works.

You can help me, use

```sh
meta unload 3
meta load <path_to_plugin>
```
And you will see exactly which signature was not found.

For example
```sh
meta load addons/surf/surfcombatcs2
```

**Comment by juandrep** [comment]
This is what i get it:

meta load addons/surfcombatcs2/surfcombatcs2
Failed to find address for sigs::UTIL_ClientPrintFilter!
Failed to load plugin addons/surfcombatcs2/surfcombatcs2 ().

**Comment by mEldevlp** [comment]
I remove a non-working UTIL_ClientPrintFilter. Download new *.so file [>here<](https://github.com/mEldevlp/surfcombat-metamod-cs2/actions/runs/6851254962). In the Artifacts section choose Linux.

If you have any troubles or it doesnt work, let me know

**Comment by juandrep** [comment]
The metamode file should be the .so file insted the .vdf?

**Comment by mEldevlp** [comment]
Just replace *.so from the archive in your folder where plugin location, ig its here `addons/surfcombatcs2/`
Do not touch *.vdf

**Comment by juandrep** [comment]
is giving this new error:

meta load addons/surfcombatcs2/surfcombatcs2
Failed to find address for sigs::UTIL_ClientPrintAll!
Failed to load plugin addons/surfcombatcs2/surfcombatcs2 ().

**Comment by mEldevlp** [comment]
Seems it doesnt work on linux now, unfortunately. I recommend change the server to windows
